version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_cinelog
    restart: always
    environment:
      MYSQL_DATABASE: cinelog_db
      MYSQL_USER: cinelog_user
      MYSQL_PASSWORD: cinelog_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cinelog_network

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    container_name: app_cinelog
    restart: always
    expose:
      - "3000"
    environment:
      DB_HOST: db_service
      DB_USER: cinelog_user
      DB_PASS: cinelog_pass
      DB_NAME: cinelog_db
      APP_PORT: 3000
    depends_on:
      - db_service
    networks:
      - cinelog_network

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_cinelog
    restart: always
    ports:
      - "2585:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - cinelog_network

# --- VOLUMES ---
volumes:
  db_data: mysql_data_${GROUP_NAME}
  driver: local

# --- NETWORKS ---
networks:
  cinelog_network:
    driver: bridge
    name: net_cinelog_${GROUP_NAME}